### PR TITLE
Update Fable.Core and FSharp.Core

### PR DESCRIPTION
**Pull request by tforkmann**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
In general, 
we try to keep FSharp.Core version as low as possible and in general it is `>= 4.7.2`.

Do we really need to upgrade FSharp.Core to the latest version?

**Comment by tforkmann** [comment]
Yeah, sadly I still have issues with the version 4.7.2 trying to update to .NET7. I changed it FSharp.Core  >= 4.7.2. Would that be ok now?
image

**Comment by tforkmann** [comment]
The ~> "twiddle-wakka" from Paket forces FShar.Core to following versions:
image

**Comment by MangelMaxime** [comment]
@tforkmann Yes, `>= 4.7.2` is good to me.

The goal is to have dependencies looking like`FSharp.Core (>= 4.7.2)` when viewed on Nuget.org:

In general, I use https://nuget.info/ to preview the result as you don't need to push a real package to Nuget.org thanks to that tool.

Steps:

1. Generate the nupkg file using `dotnet pack`
2. Import that file on https://nuget.info/
3. Check the output in the dependencies tab:

image

**Comment by tforkmann** [comment]
image
Current state at nuget...

@Dzoukr Could you please create a new prerelease like that? Thanks, Tim

**Comment by Dzoukr** [comment]
I'd love to, but

```
There was a problem while setting up the environment:
-> Error during parsing of 'C:\Dzoukr\Personal\dzoukr\Feliz.Bulma\paket.lock'.
-> invalid parameter 'net7.0' after >= or < in '>= net7.0)) (>= net472) (&& (< net6.0) (>= net7.0))'
```

Did you pushed all the versioning changes?

**Comment by Dzoukr** [comment]
I did fresh checkout and no luck :(

**Comment by tforkmann** [comment]
sadly, we have to use the newest fake for it https://github.com/fsprojects/FAKE/issues/2708 

Created a new PR for it

**Pull request merged**
